"""PPO-to-platform deployment bridge.

Loads a trained PPO model and drives it against either the live platform
(via the SDK) or a backtest session (via the REST API).  At each decision
step the bridge:

  1. Fetches the current observation (prices, positions, balances).
  2. Runs ``model.predict(obs, deterministic=True)`` to get target weights.
  3. Computes the weight delta vs the current allocation.
  4. Converts deltas to market orders: positive delta → buy, negative → sell.
  5. Filters out orders below the minimum order size (default $1 USD value).
  6. All monetary quantities are carried as :class:`decimal.Decimal`.

Modes:

- ``backtest`` — uses :class:`~agent.tools.rest_tools.PlatformRESTClient` to
  drive an existing backtest session step-by-step.  No real money changes hands.
- ``live``     — uses :class:`~agentexchange.async_client.AsyncAgentExchangeClient`
  to query live market prices and post real orders to the agent's sandbox account.

Usage::

    # Run against an existing backtest session
    python -m agent.strategies.rl.deploy \\
        --model agent/strategies/rl/models/ppo_seed42.zip \\
        --mode backtest \\
        --session-id <uuid>

    # Run live (paper-trading sandbox)
    python -m agent.strategies.rl.deploy \\
        --model agent/strategies/rl/models/ppo_seed42.zip \\
        --mode live \\
        --steps 100

Outputs::

    Trade log printed to stdout; JSONL file written to agent/reports/deploy-log-{timestamp}.jsonl
"""

from __future__ import annotations

import argparse
import asyncio
import sys
import time
from datetime import UTC, datetime
from decimal import ROUND_DOWN, Decimal
from pathlib import Path
from typing import Any

import structlog
from pydantic import BaseModel, ConfigDict

log = structlog.get_logger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────

# Minimum order value in USDT.  Orders below this threshold are skipped to
# avoid platform validation errors ("order too small") and to keep the trade
# log from being cluttered with dust trades.
_MIN_ORDER_VALUE_USDT: Decimal = Decimal("1.00")

# Weight change threshold below which no rebalancing order is issued.  This
# avoids churning on tiny allocation drifts that would be eaten by fees.
# 1% of equity — matches the MultiAssetTradingEnv's own buy/sell threshold.
_WEIGHT_DELTA_THRESHOLD: float = 0.01


# ── Data models ────────────────────────────────────────────────────────────────


class OrderRecord(BaseModel):
    """A single order generated by the bridge.

    Args:
        symbol: Trading pair (e.g. ``"BTCUSDT"``).
        side: ``"buy"`` or ``"sell"``.
        quantity: Order quantity as a string representation of a
            :class:`decimal.Decimal` (e.g. ``"0.00042153"``).
        value_usdt: Approximate USDT value of the order.
        price: Asset price used to compute the quantity.
        weight_before: Agent's portfolio weight for this asset before
            applying the model's action.
        weight_after: Target portfolio weight from the model.
        weight_delta: ``weight_after - weight_before``.  Positive means
            buying more; negative means selling.
        placed: ``True`` when the order was successfully submitted to the
            platform.  ``False`` when it was skipped (below threshold, zero
            balance) or the platform returned an error.
        error: Error message when ``placed=False`` due to an exception.
    """

    model_config = ConfigDict(frozen=True)

    symbol: str
    side: str
    quantity: str
    value_usdt: str
    price: str
    weight_before: float
    weight_after: float
    weight_delta: float
    placed: bool
    error: str | None = None


class StepRecord(BaseModel):
    """Decision step log entry.

    Args:
        step: Zero-indexed step counter.
        timestamp: ISO-8601 UTC timestamp of this step.
        equity: Total portfolio value in USDT at the start of this step.
        weights_before: Dict mapping symbol to current portfolio weight.
        weights_after: Dict mapping symbol to target weight from the model.
        orders: All orders evaluated at this step (placed or skipped).
        reasoning: Human-readable explanation of the rebalancing decision.
        error: Non-``None`` when the step raised an exception.
    """

    model_config = ConfigDict(frozen=True)

    step: int
    timestamp: str
    equity: str
    weights_before: dict[str, float]
    weights_after: dict[str, float]
    orders: list[OrderRecord]
    reasoning: str
    error: str | None = None


class DeployLog(BaseModel):
    """Complete deployment session log.

    Args:
        session_id: Backtest session UUID or ``"live"`` for live mode.
        mode: ``"backtest"`` or ``"live"``.
        model_path: Absolute path to the ``.zip`` model file.
        symbols: Asset symbols traded.
        start_equity: Starting portfolio equity.
        final_equity: Equity after the last step.
        total_steps: Number of steps completed.
        total_orders_placed: Orders that were successfully submitted.
        total_orders_skipped: Orders that fell below the minimum size or had
            zero balance.
        wall_time_sec: Total wall-clock seconds for the run.
        steps: All step records, oldest first.
    """

    model_config = ConfigDict(frozen=True)

    session_id: str
    mode: str
    model_path: str
    symbols: list[str]
    start_equity: str
    final_equity: str
    total_steps: int
    total_orders_placed: int
    total_orders_skipped: int
    wall_time_sec: float
    steps: list[StepRecord]


# ── Observation builder ────────────────────────────────────────────────────────


def _build_observation_from_platform(
    prices: dict[str, Decimal],
    positions: list[dict[str, Any]],
    balance_usdt: Decimal,
    equity: Decimal,
    symbols: list[str],
    lookback_window: int = 30,
) -> Any:
    """Build a minimal observation array compatible with the PPO model.

    The trained model expects a flat float32 array shaped to match the
    FeatureEngineeringWrapper + NormalizationWrapper output.  Since we
    cannot easily reproduce the full wrapper stack from live data, we
    construct a simplified observation using only the scalar portfolio
    features (balance ratio, position ratios).  The candle portion is
    zero-padded.

    For production use, the caller should provide recent OHLCV candles and
    compute features properly.  This simplified version is adequate for
    smoke-testing the deploy bridge end-to-end.

    Args:
        prices: Current prices keyed by symbol.
        positions: List of position dicts from the platform API.
        balance_usdt: Available cash.
        equity: Total portfolio equity.
        symbols: Ordered list of asset symbols.
        lookback_window: Lookback length used during training.

    Returns:
        Flat ``float32`` numpy array of the expected observation dimension.
    """
    import numpy as np  # noqa: PLC0415

    # Features per candle: ohlcv(5) + rsi_14(1) + macd(3) = 9 per candle per asset
    # Plus 3 feature-engineering features per period×asset.
    # Plus scalar features: balance(1) + position(1).
    # We use the dimension used by default train config.
    n_assets = len(symbols)
    candle_features = 9  # default: ohlcv + rsi_14 + macd
    fe_periods = 3  # periods=[5, 10, 20] in train.py _env_factory
    fe_features_per_period = 2  # sma_ratio, momentum
    scalar_features = 2  # balance, position

    candle_dim = lookback_window * candle_features * n_assets
    fe_dim = fe_periods * fe_features_per_period * n_assets
    obs_dim = candle_dim + fe_dim + scalar_features

    obs = np.zeros(obs_dim, dtype=np.float32)

    equity_f = float(equity) if equity > 0 else 1.0

    # Populate scalar features at the end of the observation vector.
    balance_ratio = float(balance_usdt) / equity_f
    obs[-2] = np.clip(balance_ratio, 0.0, 1.0)

    # Position ratio (fraction of equity in non-cash assets).
    position_map: dict[str, dict[str, Any]] = {}
    for pos in positions:
        sym = pos.get("symbol", "").upper()
        position_map[sym] = pos

    total_position_value = 0.0
    for sym in symbols:
        pos = position_map.get(sym, {})
        qty = float(pos.get("quantity", 0))  # float() required for numpy/SB3 interop
        price = float(prices.get(sym, Decimal("0")))  # float() required for numpy/SB3 interop
        total_position_value += qty * price

    obs[-1] = np.clip(total_position_value / equity_f, 0.0, 1.0)

    return obs


# ── Weight → order conversion ──────────────────────────────────────────────────


def _weights_to_orders(
    target_weights: Any,
    symbols: list[str],
    prices: dict[str, Decimal],
    positions: list[dict[str, Any]],
    equity: Decimal,
    balance_usdt: Decimal,
    min_order_value: Decimal = _MIN_ORDER_VALUE_USDT,
    weight_threshold: float = _WEIGHT_DELTA_THRESHOLD,
) -> list[OrderRecord]:
    """Convert target portfolio weights to a list of buy/sell orders.

    Logic mirrors :meth:`MultiAssetTradingEnv._execute_action`:

    - Normalise weights to sum <= 1.
    - For each asset compute target_value = equity * weight.
    - current_value = quantity * price.
    - delta = target_value - current_value.
    - delta > equity * weight_threshold → buy order.
    - delta < -(equity * weight_threshold) → sell order.
    - Skip if order value < min_order_value.
    - Cap sell quantity at current holding.

    All quantities are carried as :class:`decimal.Decimal` and returned as
    strings to preserve precision through JSON serialisation.

    Args:
        target_weights: ``float32`` numpy array of shape ``(n_assets,)``.
        symbols: Asset symbols matching the weight array index order.
        prices: Current prices keyed by symbol.
        positions: Position list from the platform.
        equity: Total portfolio equity in USDT.
        balance_usdt: Available cash.
        min_order_value: Minimum order value in USDT.
        weight_threshold: Minimum relative weight delta to trigger an order.

    Returns:
        List of :class:`OrderRecord` (placed or skipped).
    """
    import numpy as np  # noqa: PLC0415

    orders: list[OrderRecord] = []

    weights = np.clip(target_weights, 0.0, 1.0).astype(float)
    total_w = weights.sum()
    if total_w > 1.0:
        weights = weights / total_w

    # Build current position map.
    position_map: dict[str, dict[str, Any]] = {}
    for pos in positions:
        sym = pos.get("symbol", "").upper()
        position_map[sym] = pos

    equity_f = float(equity)
    threshold_value = equity_f * weight_threshold

    for i, symbol in enumerate(symbols):
        target_weight = float(weights[i])
        target_value = equity_f * target_weight
        price_dec = prices.get(symbol, Decimal("0"))
        price_f = float(price_dec)

        if price_f <= 0:
            log.debug("agent.strategy.rl.deploy.order.skip_zero_price", symbol=symbol)
            continue

        pos = position_map.get(symbol, {})
        current_qty = float(pos.get("quantity", 0))
        current_value = current_qty * price_f
        current_weight = current_value / max(equity_f, 1e-8)

        delta = target_value - current_value
        abs_delta = abs(delta)

        if abs_delta < threshold_value:
            # Delta is within the dead-band; no rebalancing needed.
            orders.append(
                OrderRecord(
                    symbol=symbol,
                    side="buy" if delta >= 0 else "sell",
                    quantity="0",
                    value_usdt="0",
                    price=str(price_dec),
                    weight_before=round(current_weight, 6),
                    weight_after=round(target_weight, 6),
                    weight_delta=round(target_weight - current_weight, 6),
                    placed=False,
                    error="below_threshold",
                )
            )
            continue

        if delta > 0:
            # Buy: ensure we have enough cash.
            buy_value = min(delta, float(balance_usdt))
            if buy_value < float(min_order_value):
                orders.append(
                    OrderRecord(
                        symbol=symbol,
                        side="buy",
                        quantity="0",
                        value_usdt=str(Decimal(str(round(buy_value, 8)))),
                        price=str(price_dec),
                        weight_before=round(current_weight, 6),
                        weight_after=round(target_weight, 6),
                        weight_delta=round(target_weight - current_weight, 6),
                        placed=False,
                        error="below_min_order_value",
                    )
                )
                continue

            qty_dec = (Decimal(str(buy_value)) / price_dec).quantize(
                Decimal("0.00000001"), rounding=ROUND_DOWN
            )
            orders.append(
                OrderRecord(
                    symbol=symbol,
                    side="buy",
                    quantity=str(qty_dec),
                    value_usdt=str((qty_dec * price_dec).quantize(Decimal("0.01"))),
                    price=str(price_dec),
                    weight_before=round(current_weight, 6),
                    weight_after=round(target_weight, 6),
                    weight_delta=round(target_weight - current_weight, 6),
                    placed=True,  # caller will update if placement fails
                )
            )

        else:
            # Sell: cap at current holding.
            sell_value = min(abs_delta, current_value)
            if sell_value < float(min_order_value):
                orders.append(
                    OrderRecord(
                        symbol=symbol,
                        side="sell",
                        quantity="0",
                        value_usdt=str(Decimal(str(round(sell_value, 8)))),
                        price=str(price_dec),
                        weight_before=round(current_weight, 6),
                        weight_after=round(target_weight, 6),
                        weight_delta=round(target_weight - current_weight, 6),
                        placed=False,
                        error="below_min_order_value",
                    )
                )
                continue

            sell_qty = min(
                float(Decimal(str(sell_value)) / price_dec),  # float() required for numpy/SB3 interop
                current_qty,
            )
            qty_dec = Decimal(str(sell_qty)).quantize(
                Decimal("0.00000001"), rounding=ROUND_DOWN
            )
            if qty_dec <= 0:
                orders.append(
                    OrderRecord(
                        symbol=symbol,
                        side="sell",
                        quantity="0",
                        value_usdt="0",
                        price=str(price_dec),
                        weight_before=round(current_weight, 6),
                        weight_after=round(target_weight, 6),
                        weight_delta=round(target_weight - current_weight, 6),
                        placed=False,
                        error="zero_quantity",
                    )
                )
                continue

            orders.append(
                OrderRecord(
                    symbol=symbol,
                    side="sell",
                    quantity=str(qty_dec),
                    value_usdt=str((qty_dec * price_dec).quantize(Decimal("0.01"))),
                    price=str(price_dec),
                    weight_before=round(current_weight, 6),
                    weight_after=round(target_weight, 6),
                    weight_delta=round(target_weight - current_weight, 6),
                    placed=True,  # caller will update if placement fails
                )
            )

    return orders


def _build_reasoning(
    step: int,
    weights_before: dict[str, float],
    weights_after: dict[str, float],
    orders: list[OrderRecord],
) -> str:
    """Produce a human-readable summary of the rebalancing decision.

    Args:
        step: Current step index.
        weights_before: Symbol → current weight mapping.
        weights_after: Symbol → target weight mapping.
        orders: All generated order records.

    Returns:
        Multi-line reasoning string.
    """
    placed = [o for o in orders if o.placed]
    skipped = [o for o in orders if not o.placed]

    lines: list[str] = [f"Step {step}: portfolio rebalancing decision"]

    for sym in weights_before:
        wb = weights_before.get(sym, 0.0)
        wa = weights_after.get(sym, 0.0)
        delta = wa - wb
        direction = "increase" if delta > 0 else ("decrease" if delta < 0 else "hold")
        lines.append(f"  {sym}: {wb:.2%} -> {wa:.2%} ({direction})")

    if placed:
        lines.append(f"  Orders placed: {len(placed)}")
        for o in placed:
            lines.append(f"    {o.side.upper()} {o.quantity} {o.symbol} @ {o.price} (~{o.value_usdt} USDT)")
    else:
        lines.append("  No orders placed (all below threshold or insufficient balance)")

    if skipped:
        reasons: dict[str, int] = {}
        for o in skipped:
            r = o.error or "unknown"
            reasons[r] = reasons.get(r, 0) + 1
        lines.append(f"  Orders skipped: {sum(reasons.values())} ({reasons})")

    return "\n".join(lines)


# ── PPODeployBridge ────────────────────────────────────────────────────────────


class PPODeployBridge:
    """Connects a trained PPO model to the TradeReady platform.

    Operates in two modes:

    - ``"backtest"`` — Steps through an existing backtest session using
      :class:`~agent.tools.rest_tools.PlatformRESTClient`.  Does not require
      a running market; uses historical replay.
    - ``"live"``    — Queries real-time prices and positions via the SDK
      :class:`~agentexchange.async_client.AsyncAgentExchangeClient`.

    Args:
        model_path: Path to the SB3 ``.zip`` model file.
        config: :class:`~agent.strategies.rl.config.RLConfig` instance
            providing ``platform_api_key``, ``platform_base_url``,
            ``env_symbols``, ``lookback_window``, and ``starting_balance``.
        mode: ``"backtest"`` or ``"live"``.
        min_order_value: Minimum order value in USDT.  Orders below this
            are skipped without being placed.  Default ``$1.00``.
    """

    def __init__(
        self,
        model_path: str,
        config: Any,
        mode: str = "backtest",
        min_order_value: Decimal = _MIN_ORDER_VALUE_USDT,
    ) -> None:
        if mode not in ("backtest", "live"):
            raise ValueError(f"mode must be 'backtest' or 'live', got {mode!r}")

        self._model_path = model_path
        self._config = config
        self._mode = mode
        self._min_order_value = min_order_value
        self._model: Any = None  # loaded lazily

    # ── Model loading ──────────────────────────────────────────────────────────

    def _load_model(self) -> None:
        """Load the SB3 model from disk if not already loaded."""
        if self._model is not None:
            return
        try:
            from stable_baselines3 import PPO  # noqa: PLC0415
        except ImportError:
            raise RuntimeError(
                "stable-baselines3 is not installed.  "
                "Install it with: pip install stable-baselines3"
            ) from None

        log.info("agent.strategy.rl.deploy.model_loading", path=self._model_path)
        try:
            from agent.strategies.checksum import SecurityError, verify_checksum  # noqa: PLC0415

            verify_checksum(Path(self._model_path))
        except SecurityError as exc_sec:
            log.error("agent.strategy.rl.deploy.model.checksum_mismatch", path=self._model_path, error=str(exc_sec))
            raise
        except Exception as exc_cs:  # noqa: BLE001
            log.warning("agent.strategy.rl.deploy.model.checksum_check_failed", path=self._model_path, error=str(exc_cs))
        self._model = PPO.load(self._model_path)
        log.info("agent.strategy.rl.deploy.model_loaded", path=self._model_path)

    # ── Backtest mode ─────────────────────────────────────────────────────────

    async def run_backtest(
        self,
        session_id: str,
        n_steps: int = 100,
    ) -> DeployLog:
        """Drive an existing backtest session for ``n_steps`` decisions.

        Each decision step:
          1. Fetches portfolio state from the backtest session.
          2. Builds an observation array.
          3. Runs ``model.predict()``.
          4. Converts weights to orders via :func:`_weights_to_orders`.
          5. Places each "placed=True" order via the backtest trade endpoint.
          6. Advances the session by one candle step.

        Args:
            session_id: UUID of an already-created and started backtest
                session.
            n_steps: Number of candle steps to execute.

        Returns:
            :class:`DeployLog` with the full trade history.
        """
        import httpx  # noqa: PLC0415

        self._load_model()
        t_start = time.monotonic()
        step_records: list[StepRecord] = []
        start_equity = Decimal(str(self._config.starting_balance))
        final_equity = start_equity

        base_url = self._config.platform_base_url.rstrip("/")
        headers = {"X-API-Key": self._config.platform_api_key}

        async with httpx.AsyncClient(base_url=base_url, headers=headers, timeout=30.0) as client:
            log.info("agent.strategy.rl.deploy.backtest.start", session_id=session_id, n_steps=n_steps)

            for step_idx in range(n_steps):
                step_error: str | None = None
                orders_for_step: list[OrderRecord] = []
                ts = datetime.now(UTC).isoformat()

                try:
                    # Advance the session by one step to get current state.
                    _resp = await client.post(
                        f"/api/v1/backtest/{session_id}/step/batch",
                        json={"steps": 1},
                    )
                    _resp.raise_for_status()
                    step_result: dict[str, Any] = _resp.json()
                    portfolio = step_result.get("portfolio", {})
                    prices_raw: dict[str, Any] = step_result.get("prices", {})

                    equity_f = float(portfolio.get("total_equity", self._config.starting_balance))
                    balance_f = float(portfolio.get("cash_balance", equity_f))
                    positions: list[dict[str, Any]] = portfolio.get("positions", [])

                    equity = Decimal(str(round(equity_f, 8)))
                    balance_usdt = Decimal(str(round(balance_f, 8)))
                    final_equity = equity

                    # Convert prices to Decimal.
                    prices: dict[str, Decimal] = {}
                    for sym in self._config.env_symbols:
                        raw_price = prices_raw.get(sym, prices_raw.get(sym.upper(), 0))
                        # float() required for numpy/SB3 interop
                        prices[sym] = Decimal(str(float(raw_price))) if raw_price else Decimal("0")

                    # Compute weights before.
                    weights_before: dict[str, float] = {}
                    position_map = {p.get("symbol", "").upper(): p for p in positions}
                    for sym in self._config.env_symbols:
                        pos = position_map.get(sym, {})
                        # float() required for numpy/SB3 interop
                        qty = float(pos.get("quantity", 0))
                        price_f = float(prices.get(sym, Decimal("0")))
                        weights_before[sym] = (qty * price_f) / max(equity_f, 1e-8)

                    # Build observation and predict.
                    obs = _build_observation_from_platform(
                        prices=prices,
                        positions=positions,
                        balance_usdt=balance_usdt,
                        equity=equity,
                        symbols=self._config.env_symbols,
                        lookback_window=self._config.lookback_window,
                    )
                    target_weights, _ = await asyncio.to_thread(
                        self._model.predict, obs, deterministic=True
                    )

                    # Convert to orders.
                    orders_for_step = _weights_to_orders(
                        target_weights=target_weights,
                        symbols=self._config.env_symbols,
                        prices=prices,
                        positions=positions,
                        equity=equity,
                        balance_usdt=balance_usdt,
                        min_order_value=self._min_order_value,
                    )

                    # Place orders.
                    updated_orders: list[OrderRecord] = []
                    for order in orders_for_step:
                        if not order.placed:
                            updated_orders.append(order)
                            continue
                        try:
                            _order_resp = await client.post(
                                f"/api/v1/backtest/{session_id}/trade/order",
                                json={
                                    "symbol": order.symbol,
                                    "side": order.side,
                                    "type": "market",
                                    "quantity": order.quantity,
                                },
                            )
                            _order_resp.raise_for_status()
                            updated_orders.append(order)
                            log.debug(
                                "agent.strategy.rl.deploy.order.placed",
                                step=step_idx,
                                symbol=order.symbol,
                                side=order.side,
                                qty=order.quantity,
                                value_usdt=order.value_usdt,
                            )
                        except Exception as exc:  # noqa: BLE001
                            updated_orders.append(
                                order.model_copy(
                                    update={"placed": False, "error": str(exc)}
                                )
                            )
                            log.warning(
                                "agent.strategy.rl.deploy.order.failed",
                                step=step_idx,
                                symbol=order.symbol,
                                side=order.side,
                                error=str(exc),
                            )
                    orders_for_step = updated_orders

                    # Compute weights after from target.
                    import numpy as np  # noqa: PLC0415

                    ws = np.clip(target_weights, 0.0, 1.0)
                    total_w = ws.sum()
                    if total_w > 1.0:
                        ws = ws / total_w
                    weights_after = {
                        sym: round(float(ws[i]), 6)
                        for i, sym in enumerate(self._config.env_symbols)
                    }

                    reasoning = _build_reasoning(
                        step=step_idx,
                        weights_before=weights_before,
                        weights_after=weights_after,
                        orders=orders_for_step,
                    )

                    # Check terminal condition — the backtest API uses "is_complete".
                    done = bool(
                        step_result.get("is_complete")
                        or step_result.get("terminated")
                        or step_result.get("done")
                    )

                except Exception as exc:  # noqa: BLE001
                    log.exception("agent.strategy.rl.deploy.step.failed", step=step_idx, error=str(exc))
                    step_error = str(exc)
                    equity = final_equity
                    weights_before = {s: 0.0 for s in self._config.env_symbols}
                    weights_after = {s: 0.0 for s in self._config.env_symbols}
                    reasoning = f"Step {step_idx}: error — {exc}"
                    done = False

                step_records.append(
                    StepRecord(
                        step=step_idx,
                        timestamp=ts,
                        equity=str(final_equity),
                        weights_before=weights_before,
                        weights_after=weights_after,
                        orders=orders_for_step,
                        reasoning=reasoning,
                        error=step_error,
                    )
                )

                if done:
                    log.info("agent.strategy.rl.deploy.backtest.terminated", step=step_idx)
                    break

        total_placed = sum(1 for sr in step_records for o in sr.orders if o.placed)
        total_skipped = sum(1 for sr in step_records for o in sr.orders if not o.placed)

        return DeployLog(
            session_id=session_id,
            mode="backtest",
            model_path=self._model_path,
            symbols=list(self._config.env_symbols),
            start_equity=str(start_equity),
            final_equity=str(final_equity),
            total_steps=len(step_records),
            total_orders_placed=total_placed,
            total_orders_skipped=total_skipped,
            wall_time_sec=round(time.monotonic() - t_start, 2),
            steps=step_records,
        )

    # ── Live mode ─────────────────────────────────────────────────────────────

    async def run_live(
        self,
        n_steps: int = 10,
        step_interval_sec: float = 0.0,
    ) -> DeployLog:
        """Drive real-time paper trading for ``n_steps`` decisions.

        Uses the async SDK client to fetch live prices, positions, and
        balances.  Orders are placed via ``client.place_market_order()``.
        Between steps the bridge optionally waits ``step_interval_sec``
        seconds to simulate a candle-aligned tick rate.

        Args:
            n_steps: Number of decision steps to execute.
            step_interval_sec: Seconds to wait between steps.  Set to 3600
                for hourly candle alignment.  Default 0 (no wait) for
                testing.

        Returns:
            :class:`DeployLog` with the full trade history.
        """
        try:
            from agentexchange import AsyncAgentExchangeClient  # noqa: PLC0415
        except ImportError:
            raise RuntimeError(
                "agentexchange SDK is not installed.  "
                "Run: pip install -e sdk/"
            ) from None

        self._load_model()
        t_start = time.monotonic()
        step_records: list[StepRecord] = []

        # Fetch starting equity for the log.
        async with AsyncAgentExchangeClient(
            api_key=self._config.platform_api_key,
            base_url=self._config.platform_base_url,
        ) as client:
            portfolio_resp = await client.get_portfolio()
            start_equity = Decimal(str(portfolio_resp.total_value))
            final_equity = start_equity

            log.info(
                "agent.strategy.rl.deploy.live.start",
                n_steps=n_steps,
                symbols=self._config.env_symbols,
                start_equity=str(start_equity),
            )

            for step_idx in range(n_steps):
                step_error: str | None = None
                orders_for_step: list[OrderRecord] = []
                ts = datetime.now(UTC).isoformat()

                try:
                    # Refresh state.
                    portfolio_resp = await client.get_portfolio()
                    equity_f = float(portfolio_resp.total_value)
                    balance_f = sum(
                        float(b.available)
                        for b in await client.get_balance()
                        if b.asset == "USDT"
                    )
                    positions_sdk = await client.get_positions()
                    positions: list[dict[str, Any]] = [
                        {
                            "symbol": p.symbol,
                            "quantity": str(p.quantity),
                            "market_value": str(p.market_value),
                        }
                        for p in positions_sdk
                    ]

                    equity = Decimal(str(round(equity_f, 8)))
                    balance_usdt = Decimal(str(round(balance_f, 8)))
                    final_equity = equity

                    # Fetch prices.
                    prices: dict[str, Decimal] = {}
                    for sym in self._config.env_symbols:
                        try:
                            price_resp = await client.get_price(sym)
                            prices[sym] = Decimal(str(price_resp.price))
                        except Exception:  # noqa: BLE001
                            prices[sym] = Decimal("0")

                    # Compute weights before.
                    weights_before: dict[str, float] = {}
                    position_map = {p.get("symbol", "").upper(): p for p in positions}
                    for sym in self._config.env_symbols:
                        pos = position_map.get(sym, {})
                        qty = float(pos.get("quantity", 0))  # float() required for numpy/SB3 interop
                        price_f = float(prices.get(sym, Decimal("0")))  # float() required for numpy/SB3 interop
                        weights_before[sym] = (qty * price_f) / max(equity_f, 1e-8)

                    # Build observation and predict.
                    obs = _build_observation_from_platform(
                        prices=prices,
                        positions=positions,
                        balance_usdt=balance_usdt,
                        equity=equity,
                        symbols=self._config.env_symbols,
                        lookback_window=self._config.lookback_window,
                    )
                    target_weights, _ = await asyncio.to_thread(
                        self._model.predict, obs, deterministic=True
                    )

                    # Convert to orders.
                    orders_for_step = _weights_to_orders(
                        target_weights=target_weights,
                        symbols=self._config.env_symbols,
                        prices=prices,
                        positions=positions,
                        equity=equity,
                        balance_usdt=balance_usdt,
                        min_order_value=self._min_order_value,
                    )

                    # Place orders.
                    updated_orders: list[OrderRecord] = []
                    for order in orders_for_step:
                        if not order.placed:
                            updated_orders.append(order)
                            continue
                        try:
                            await client.place_market_order(
                                symbol=order.symbol,
                                side=order.side,
                                quantity=order.quantity,
                            )
                            updated_orders.append(order)
                            log.info(
                                "agent.strategy.rl.deploy.order.placed",
                                step=step_idx,
                                symbol=order.symbol,
                                side=order.side,
                                qty=order.quantity,
                                value_usdt=order.value_usdt,
                            )
                        except Exception as exc:  # noqa: BLE001
                            updated_orders.append(
                                order.model_copy(
                                    update={"placed": False, "error": str(exc)}
                                )
                            )
                            log.warning(
                                "agent.strategy.rl.deploy.order.failed",
                                step=step_idx,
                                symbol=order.symbol,
                                side=order.side,
                                error=str(exc),
                            )
                    orders_for_step = updated_orders

                    import numpy as np  # noqa: PLC0415

                    ws = np.clip(target_weights, 0.0, 1.0)
                    total_w = ws.sum()
                    if total_w > 1.0:
                        ws = ws / total_w
                    weights_after = {
                        sym: round(float(ws[i]), 6)
                        for i, sym in enumerate(self._config.env_symbols)
                    }

                    reasoning = _build_reasoning(
                        step=step_idx,
                        weights_before=weights_before,
                        weights_after=weights_after,
                        orders=orders_for_step,
                    )

                except Exception as exc:  # noqa: BLE001
                    log.exception("agent.strategy.rl.deploy.step.failed", step=step_idx, error=str(exc))
                    step_error = str(exc)
                    equity = final_equity
                    weights_before = {s: 0.0 for s in self._config.env_symbols}
                    weights_after = {s: 0.0 for s in self._config.env_symbols}
                    reasoning = f"Step {step_idx}: error — {exc}"

                step_records.append(
                    StepRecord(
                        step=step_idx,
                        timestamp=ts,
                        equity=str(final_equity),
                        weights_before=weights_before,
                        weights_after=weights_after,
                        orders=orders_for_step,
                        reasoning=reasoning,
                        error=step_error,
                    )
                )

                if step_interval_sec > 0 and step_idx < n_steps - 1:
                    await asyncio.sleep(step_interval_sec)

        total_placed = sum(1 for sr in step_records for o in sr.orders if o.placed)
        total_skipped = sum(1 for sr in step_records for o in sr.orders if not o.placed)

        return DeployLog(
            session_id="live",
            mode="live",
            model_path=self._model_path,
            symbols=list(self._config.env_symbols),
            start_equity=str(start_equity),
            final_equity=str(final_equity),
            total_steps=len(step_records),
            total_orders_placed=total_placed,
            total_orders_skipped=total_skipped,
            wall_time_sec=round(time.monotonic() - t_start, 2),
            steps=step_records,
        )


# ── Persistence ────────────────────────────────────────────────────────────────


def _save_deploy_log(deploy_log: DeployLog, output_dir: Path) -> Path:
    """Persist the deploy log as a JSON file.

    Args:
        deploy_log: Completed :class:`DeployLog`.
        output_dir: Directory to write to.  Created if missing.

    Returns:
        Absolute path to the written file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
    filename = f"deploy-log-{deploy_log.mode}-{ts}.json"
    path = output_dir / filename
    path.write_text(deploy_log.model_dump_json(indent=2), encoding="utf-8")
    log.info("agent.strategy.rl.deploy.log_saved", path=str(path))
    return path


# ── Logging setup ──────────────────────────────────────────────────────────────


def _configure_logging(verbose: bool) -> None:
    """Configure structlog for the deploy CLI.

    Args:
        verbose: When ``True``, enable DEBUG-level output.
    """
    from agent.logging import configure_agent_logging  # noqa: PLC0415

    configure_agent_logging(log_level="DEBUG" if verbose else "INFO")


# ── CLI ────────────────────────────────────────────────────────────────────────


def _build_parser() -> argparse.ArgumentParser:
    """Build the CLI argument parser.

    Returns:
        Configured :class:`argparse.ArgumentParser`.
    """
    p = argparse.ArgumentParser(
        prog="python -m agent.strategies.rl.deploy",
        description=(
            "Deploy a trained PPO model against the TradeReady platform.  "
            "Use --mode backtest (safe) or --mode live (paper-trading sandbox)."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--model",
        type=str,
        default=None,
        metavar="PATH",
        help="Path to the .zip model file (e.g. agent/strategies/rl/models/ppo_seed42.zip).",
    )
    p.add_argument(
        "--mode",
        choices=["backtest", "live"],
        default="backtest",
        help="Execution mode: 'backtest' steps an existing session; 'live' uses real-time data.",
    )
    p.add_argument(
        "--session-id",
        type=str,
        default=None,
        metavar="UUID",
        help="(backtest mode) Existing backtest session UUID to step through.",
    )
    p.add_argument(
        "--steps",
        type=int,
        default=100,
        metavar="N",
        help="Number of decision steps to execute.",
    )
    p.add_argument(
        "--step-interval",
        type=float,
        default=0.0,
        metavar="SEC",
        help="(live mode) Seconds to wait between steps (e.g. 3600 for hourly candles).",
    )
    p.add_argument(
        "--min-order-value",
        type=float,
        default=1.0,
        metavar="USDT",
        help="Minimum order value in USDT.  Orders below this are skipped.",
    )
    p.add_argument(
        "--base-url",
        type=str,
        default=None,
        metavar="URL",
        help="Platform REST API base URL.",
    )
    p.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        metavar="DIR",
        help="Directory to write the deploy log JSON.",
    )
    p.add_argument(
        "--verbose",
        action="store_true",
        help="Enable DEBUG-level log output.",
    )
    return p


def main() -> None:
    """CLI entry point.

    Loads :class:`RLConfig`, applies CLI overrides, constructs a
    :class:`PPODeployBridge`, runs the requested mode, saves the deploy log,
    and prints a summary.
    """
    from agent.strategies.rl.config import RLConfig  # noqa: PLC0415

    p = _build_parser()
    args = p.parse_args()
    _configure_logging(args.verbose)

    try:
        config = RLConfig()
    except Exception as exc:
        log.error("agent.strategy.rl.deploy.config.load_failed", error=str(exc))
        sys.exit(1)

    overrides: dict[str, Any] = {}
    if args.base_url is not None:
        overrides["platform_base_url"] = args.base_url
    if overrides:
        config = config.model_copy(update=overrides)

    if not config.platform_api_key:
        log.error(
            "agent.strategy.rl.deploy.config.missing_api_key",
            hint="Set RL_PLATFORM_API_KEY in agent/.env or as environment variable",
        )
        sys.exit(1)

    # Resolve model path.
    model_path: str | None = args.model
    if model_path is None:
        # Auto-discover: pick ppo_seed42.zip if it exists, else first available.
        candidate = config.models_dir / "ppo_seed42.zip"
        if candidate.exists():
            model_path = str(candidate)
        else:
            found = sorted(config.models_dir.glob("ppo_seed*.zip"))
            if found:
                model_path = str(found[0])

    if model_path is None or not Path(model_path).exists():
        log.error(
            "agent.strategy.rl.deploy.model_not_found",
            path=model_path,
            hint="Train a model first with: python -m agent.strategies.rl.runner",
        )
        sys.exit(1)

    output_dir: Path = (
        args.output_dir
        if args.output_dir is not None
        else Path(__file__).parent.parent.parent / "reports"
    )

    bridge = PPODeployBridge(
        model_path=model_path,
        config=config,
        mode=args.mode,
        min_order_value=Decimal(str(args.min_order_value)),
    )

    try:
        if args.mode == "backtest":
            if args.session_id is None:
                log.error(
                    "agent.strategy.rl.deploy.missing_session_id",
                    hint="Provide --session-id <uuid> for backtest mode.",
                )
                sys.exit(1)
            deploy_log = asyncio.run(
                bridge.run_backtest(session_id=args.session_id, n_steps=args.steps)
            )
        else:
            deploy_log = asyncio.run(
                bridge.run_live(
                    n_steps=args.steps,
                    step_interval_sec=args.step_interval,
                )
            )
    except KeyboardInterrupt:
        log.info("agent.strategy.rl.deploy.interrupted")
        sys.exit(0)
    except Exception as exc:
        log.exception("agent.strategy.rl.deploy.failed", error=str(exc))
        sys.exit(1)

    saved_path = _save_deploy_log(deploy_log, output_dir)

    # Log deploy summary.
    log.info(
        "agent.strategy.rl.deploy.summary",
        mode=deploy_log.mode,
        session_id=deploy_log.session_id,
        model_path=deploy_log.model_path,
        total_steps=deploy_log.total_steps,
        orders_placed=deploy_log.total_orders_placed,
        orders_skipped=deploy_log.total_orders_skipped,
        start_equity=str(deploy_log.start_equity),
        final_equity=str(deploy_log.final_equity),
        wall_time_sec=round(deploy_log.wall_time_sec, 1),
        log_file=str(saved_path),
    )


if __name__ == "__main__":
    main()
